### ISSUE TITLE
Statik url kullanmamak daha iyi

### ISSUE THREAD

**Issue by ismailbayram** [Doganberk/doganblog#1]
https://github.com/Doganberk/doganblog/blob/81a97b02e1b00f61cd2eacfd432a44944328bccd/djangoblog/templates/base_layout.html#L17

bu tarz url leri tek bir yerden yonetebiliyor olman lazim, yani bir degisken adi vererek url i buraya bassan daha iyi olur. ornek :  `url('base-layout-form-url')`

**Comment by Doganberk** [comment]
Merhaba, yazdığım şekilde bir kullanımın doğru olmadığını biliyorum fakat
<form class="logout-link" action="{%url'accounts:logout'%}" method="post"> 
şeklinde yazmıştım başta ancak çözemediğim bir hata vermeye başladı. Bu yüzden değiştirmiştim.

**Comment by ismailbayram** [comment]
django template function lara bakabilirsin, ayrica template engine olarak django nun default'unu degil de jinja2 yi tavsiye ederim. Daha efektif.
